version: '3'

services:

    php:
        build:
            context: ./docker/php
        ports:
            - 9000:9000
        volumes:
            - ./:/var/www/meeting
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        environment:
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}

    nginx:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./:/var/www/meeting
            - ${CONF_MAP}
            - ${SSL_CRT_MAP}
            - ${SSL_KEY_MAP}
        depends_on:
            - php

    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        depends_on:
            - php
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}

